name = "air-quality-monitor"
compatibility_date = "2024-01-01"
account_id = "4dbff05b78328d3507de825e12499c40"
zone_id = "80a138846f18cdf5aa3872aaefaee066"
main = "workers-site/index.js"

[build]
command = "npm run build"

[site]
bucket = ".next"

[env.production]
NODE_ENV = "production"

pages_build_output_dir = ".next"

# Custom domain configuration
routes = [
  { pattern = "aqiairquality.com", custom_domain = true }
] 